# Generated by Django 4.1.5 on 2023-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_first_name_alter_siteuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
