# Generated by Django 4.1.5 on 2023-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
