# Generated by Django 4.1.5 on 2023-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_created_at'),
        ('tasks', '0007_taskslabels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='labels',
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(through="tasks.TasksLabels", to='labels.label', verbose_name='Метки')
        ),
    ]
