name: tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.x
      - name: Install dependencies
        run: |
          pip install poetry
          make install
          pip install -r requirements.txt
      - name: Run tests
        run: |
          make test
      - name: Create reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: test
        run: |
          make test-cov
          make xml
      - name: sending reporter
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN"
