# Generated by Django 4.1.5 on 2023-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuses',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
